### ISSUE TITLE
Warning on Ruby 2.4.0

### ISSUE THREAD

**Issue by fabianfrz** [aquasync/ruby-ole#21]
/home/username/.gem/ruby/2.4.0/gems/ruby-ole-1.2.12/lib/ole/support.rb:201: warning: constant ::Fixnum is deprecated

**Comment by fabianfrz** [comment]
ok, looks like there is already a pull request for that issue: #19

**Comment by aquasync** [comment]
Yep, that has been merged now and release as 1.2.12.1, so should be fine now.
